name: Build
on: [pull_request, push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: akerl/action-checkout@v2.0.0
    - name: Install Ruby
      uses: akerl/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Install deps
      run: bundle install
    - name: Rake
      run: bundle exec rake
    - name: Log in to Rubygems
      run: 'mkdir -p ~/.gem && echo ":rubygems_api_key: ${RUBY_TOKEN}" > ~/.gem/credentials && chmod 600 ~/.gem/credentials'
      if: startsWith(github.ref, 'refs/tags/')
      env:
        RUBY_TOKEN: ${{ secrets.RUBY_TOKEN }}
    - name: Release
      run: bundle exec rake release
      if: startsWith(github.ref, 'refs/tags/')
    - name: Notify on success
      if: success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: akerl/github-action-slack-notify-build@v1.1.1
      with:
        channel_id: ${{ secrets.SLACK_BOT_CHANNEL }}
        status: success
        color: good
    - name: Notify on failure
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: akerl/github-action-slack-notify-build@v1.1.1
      with:
        channel_id: ${{ secrets.SLACK_BOT_CHANNEL }}
        status: failed
        color: danger

